package com.ghostchu.btn.sparkle.module.analyse.proto;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: peer.proto
// Protobuf Java Version: 4.29.1

public final class Peer {
    private Peer() {
    }

    static {
        com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
                com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
                /* major= */ 4,
                /* minor= */ 29,
                /* patch= */ 1,
                /* suffix= */ "",
                Peer.class.getName());
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }

    /**
     * Protobuf enum {@code PeerEvent}
     */
    public enum PeerEvent
            implements com.google.protobuf.ProtocolMessageEnum {
        /**
         * <code>Unknown = 0;</code>
         */
        Unknown(0),
        /**
         * <code>Started = 1;</code>
         */
        Started(1),
        /**
         * <code>Stopped = 2;</code>
         */
        Stopped(2),
        /**
         * <code>Completed = 3;</code>
         */
        Completed(3),
        UNRECOGNIZED(-1),
        ;

        static {
            com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
                    com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
                    /* major= */ 4,
                    /* minor= */ 29,
                    /* patch= */ 1,
                    /* suffix= */ "",
                    PeerEvent.class.getName());
        }

        /**
         * <code>Unknown = 0;</code>
         */
        public static final int Unknown_VALUE = 0;
        /**
         * <code>Started = 1;</code>
         */
        public static final int Started_VALUE = 1;
        /**
         * <code>Stopped = 2;</code>
         */
        public static final int Stopped_VALUE = 2;
        /**
         * <code>Completed = 3;</code>
         */
        public static final int Completed_VALUE = 3;


        public final int getNumber() {
            if (this == UNRECOGNIZED) {
                throw new IllegalArgumentException(
                        "Can't get the number of an unknown enum value.");
            }
            return value;
        }

        /**
         * @param value The numeric wire value of the corresponding enum entry.
         * @return The enum associated with the given numeric wire value.
         * @deprecated Use {@link #forNumber(int)} instead.
         */
        @Deprecated
        public static PeerEvent valueOf(int value) {
            return forNumber(value);
        }

        /**
         * @param value The numeric wire value of the corresponding enum entry.
         * @return The enum associated with the given numeric wire value.
         */
        public static PeerEvent forNumber(int value) {
            switch (value) {
                case 0:
                    return Unknown;
                case 1:
                    return Started;
                case 2:
                    return Stopped;
                case 3:
                    return Completed;
                default:
                    return null;
            }
        }

        public static com.google.protobuf.Internal.EnumLiteMap<PeerEvent>
        internalGetValueMap() {
            return internalValueMap;
        }

        private static final com.google.protobuf.Internal.EnumLiteMap<
                PeerEvent> internalValueMap =
                new com.google.protobuf.Internal.EnumLiteMap<PeerEvent>() {
                    public PeerEvent findValueByNumber(int number) {
                        return PeerEvent.forNumber(number);
                    }
                };

        public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
            if (this == UNRECOGNIZED) {
                throw new IllegalStateException(
                        "Can't get the descriptor of an unrecognized enum value.");
            }
            return getDescriptor().getValues().get(ordinal());
        }

        public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
            return getDescriptor();
        }

        public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
            return Peer.getDescriptor().getEnumTypes().get(0);
        }

        private static final PeerEvent[] VALUES = values();

        public static PeerEvent valueOf(
                com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
            if (desc.getType() != getDescriptor()) {
                throw new IllegalArgumentException(
                        "EnumValueDescriptor is not for this type.");
            }
            if (desc.getIndex() == -1) {
                return UNRECOGNIZED;
            }
            return VALUES[desc.getIndex()];
        }

        private final int value;

        private PeerEvent(int value) {
            this.value = value;
        }

        // @@protoc_insertion_point(enum_scope:PeerEvent)
    }

    public interface IPInfoOrBuilder extends
            // @@protoc_insertion_point(interface_extends:IPInfo)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>bytes client_ip = 1;</code>
         *
         * @return The clientIp.
         */
        com.google.protobuf.ByteString getClientIp();

        /**
         * <code>bytes report_ip = 2;</code>
         *
         * @return The reportIp.
         */
        com.google.protobuf.ByteString getReportIp();

        /**
         * <code>bytes report_v4 = 3;</code>
         *
         * @return The reportV4.
         */
        com.google.protobuf.ByteString getReportV4();

        /**
         * <code>bytes report_v6 = 4;</code>
         *
         * @return The reportV6.
         */
        com.google.protobuf.ByteString getReportV6();
    }

    /**
     * Protobuf type {@code IPInfo}
     */
    public static final class IPInfo extends
            com.google.protobuf.GeneratedMessage implements
            // @@protoc_insertion_point(message_implements:IPInfo)
            IPInfoOrBuilder {
        private static final long serialVersionUID = 0L;

        static {
            com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
                    com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
                    /* major= */ 4,
                    /* minor= */ 29,
                    /* patch= */ 1,
                    /* suffix= */ "",
                    IPInfo.class.getName());
        }

        // Use IPInfo.newBuilder() to construct.
        private IPInfo(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
            super(builder);
        }

        private IPInfo() {
            clientIp_ = com.google.protobuf.ByteString.EMPTY;
            reportIp_ = com.google.protobuf.ByteString.EMPTY;
            reportV4_ = com.google.protobuf.ByteString.EMPTY;
            reportV6_ = com.google.protobuf.ByteString.EMPTY;
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return Peer.internal_static_IPInfo_descriptor;
        }

        @Override
        protected FieldAccessorTable
        internalGetFieldAccessorTable() {
            return Peer.internal_static_IPInfo_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            IPInfo.class, Builder.class);
        }

        public static final int CLIENT_IP_FIELD_NUMBER = 1;
        private com.google.protobuf.ByteString clientIp_ = com.google.protobuf.ByteString.EMPTY;

        /**
         * <code>bytes client_ip = 1;</code>
         *
         * @return The clientIp.
         */
        @Override
        public com.google.protobuf.ByteString getClientIp() {
            return clientIp_;
        }

        public static final int REPORT_IP_FIELD_NUMBER = 2;
        private com.google.protobuf.ByteString reportIp_ = com.google.protobuf.ByteString.EMPTY;

        /**
         * <code>bytes report_ip = 2;</code>
         *
         * @return The reportIp.
         */
        @Override
        public com.google.protobuf.ByteString getReportIp() {
            return reportIp_;
        }

        public static final int REPORT_V4_FIELD_NUMBER = 3;
        private com.google.protobuf.ByteString reportV4_ = com.google.protobuf.ByteString.EMPTY;

        /**
         * <code>bytes report_v4 = 3;</code>
         *
         * @return The reportV4.
         */
        @Override
        public com.google.protobuf.ByteString getReportV4() {
            return reportV4_;
        }

        public static final int REPORT_V6_FIELD_NUMBER = 4;
        private com.google.protobuf.ByteString reportV6_ = com.google.protobuf.ByteString.EMPTY;

        /**
         * <code>bytes report_v6 = 4;</code>
         *
         * @return The reportV6.
         */
        @Override
        public com.google.protobuf.ByteString getReportV6() {
            return reportV6_;
        }

        private byte memoizedIsInitialized = -1;

        @Override
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        @Override
        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (!clientIp_.isEmpty()) {
                output.writeBytes(1, clientIp_);
            }
            if (!reportIp_.isEmpty()) {
                output.writeBytes(2, reportIp_);
            }
            if (!reportV4_.isEmpty()) {
                output.writeBytes(3, reportV4_);
            }
            if (!reportV6_.isEmpty()) {
                output.writeBytes(4, reportV6_);
            }
            getUnknownFields().writeTo(output);
        }

        @Override
        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (!clientIp_.isEmpty()) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBytesSize(1, clientIp_);
            }
            if (!reportIp_.isEmpty()) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBytesSize(2, reportIp_);
            }
            if (!reportV4_.isEmpty()) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBytesSize(3, reportV4_);
            }
            if (!reportV6_.isEmpty()) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBytesSize(4, reportV6_);
            }
            size += getUnknownFields().getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @Override
        public boolean equals(final Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof IPInfo)) {
                return super.equals(obj);
            }
            IPInfo other = (IPInfo) obj;

            if (!getClientIp()
                    .equals(other.getClientIp())) return false;
            if (!getReportIp()
                    .equals(other.getReportIp())) return false;
            if (!getReportV4()
                    .equals(other.getReportV4())) return false;
            if (!getReportV6()
                    .equals(other.getReportV6())) return false;
            if (!getUnknownFields().equals(other.getUnknownFields())) return false;
            return true;
        }

        @Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            hash = (37 * hash) + CLIENT_IP_FIELD_NUMBER;
            hash = (53 * hash) + getClientIp().hashCode();
            hash = (37 * hash) + REPORT_IP_FIELD_NUMBER;
            hash = (53 * hash) + getReportIp().hashCode();
            hash = (37 * hash) + REPORT_V4_FIELD_NUMBER;
            hash = (53 * hash) + getReportV4().hashCode();
            hash = (37 * hash) + REPORT_V6_FIELD_NUMBER;
            hash = (53 * hash) + getReportV6().hashCode();
            hash = (29 * hash) + getUnknownFields().hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static IPInfo parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static IPInfo parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static IPInfo parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static IPInfo parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static IPInfo parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static IPInfo parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static IPInfo parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessage
                    .parseWithIOException(PARSER, input);
        }

        public static IPInfo parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessage
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static IPInfo parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessage
                    .parseDelimitedWithIOException(PARSER, input);
        }

        public static IPInfo parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessage
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }

        public static IPInfo parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessage
                    .parseWithIOException(PARSER, input);
        }

        public static IPInfo parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessage
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        @Override
        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(IPInfo prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        @Override
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @Override
        protected Builder newBuilderForType(
                BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        /**
         * Protobuf type {@code IPInfo}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessage.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:IPInfo)
                IPInfoOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return Peer.internal_static_IPInfo_descriptor;
            }

            @Override
            protected FieldAccessorTable
            internalGetFieldAccessorTable() {
                return Peer.internal_static_IPInfo_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                IPInfo.class, Builder.class);
            }

            // Construct using Peer.IPInfo.newBuilder()
            private Builder() {

            }

            private Builder(
                    BuilderParent parent) {
                super(parent);

            }

            @Override
            public Builder clear() {
                super.clear();
                bitField0_ = 0;
                clientIp_ = com.google.protobuf.ByteString.EMPTY;
                reportIp_ = com.google.protobuf.ByteString.EMPTY;
                reportV4_ = com.google.protobuf.ByteString.EMPTY;
                reportV6_ = com.google.protobuf.ByteString.EMPTY;
                return this;
            }

            @Override
            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return Peer.internal_static_IPInfo_descriptor;
            }

            @Override
            public IPInfo getDefaultInstanceForType() {
                return IPInfo.getDefaultInstance();
            }

            @Override
            public IPInfo build() {
                IPInfo result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            @Override
            public IPInfo buildPartial() {
                IPInfo result = new IPInfo(this);
                if (bitField0_ != 0) {
                    buildPartial0(result);
                }
                onBuilt();
                return result;
            }

            private void buildPartial0(IPInfo result) {
                int from_bitField0_ = bitField0_;
                if (((from_bitField0_ & 0x00000001) != 0)) {
                    result.clientIp_ = clientIp_;
                }
                if (((from_bitField0_ & 0x00000002) != 0)) {
                    result.reportIp_ = reportIp_;
                }
                if (((from_bitField0_ & 0x00000004) != 0)) {
                    result.reportV4_ = reportV4_;
                }
                if (((from_bitField0_ & 0x00000008) != 0)) {
                    result.reportV6_ = reportV6_;
                }
            }

            @Override
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof IPInfo) {
                    return mergeFrom((IPInfo) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(IPInfo other) {
                if (other == IPInfo.getDefaultInstance()) return this;
                if (other.getClientIp() != com.google.protobuf.ByteString.EMPTY) {
                    setClientIp(other.getClientIp());
                }
                if (other.getReportIp() != com.google.protobuf.ByteString.EMPTY) {
                    setReportIp(other.getReportIp());
                }
                if (other.getReportV4() != com.google.protobuf.ByteString.EMPTY) {
                    setReportV4(other.getReportV4());
                }
                if (other.getReportV6() != com.google.protobuf.ByteString.EMPTY) {
                    setReportV6(other.getReportV6());
                }
                this.mergeUnknownFields(other.getUnknownFields());
                onChanged();
                return this;
            }

            @Override
            public final boolean isInitialized() {
                return true;
            }

            @Override
            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                if (extensionRegistry == null) {
                    throw new NullPointerException();
                }
                try {
                    boolean done = false;
                    while (!done) {
                        int tag = input.readTag();
                        switch (tag) {
                            case 0:
                                done = true;
                                break;
                            case 10: {
                                clientIp_ = input.readBytes();
                                bitField0_ |= 0x00000001;
                                break;
                            } // case 10
                            case 18: {
                                reportIp_ = input.readBytes();
                                bitField0_ |= 0x00000002;
                                break;
                            } // case 18
                            case 26: {
                                reportV4_ = input.readBytes();
                                bitField0_ |= 0x00000004;
                                break;
                            } // case 26
                            case 34: {
                                reportV6_ = input.readBytes();
                                bitField0_ |= 0x00000008;
                                break;
                            } // case 34
                            default: {
                                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                                    done = true; // was an endgroup tag
                                }
                                break;
                            } // default:
                        } // switch (tag)
                    } // while (!done)
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    throw e.unwrapIOException();
                } finally {
                    onChanged();
                } // finally
                return this;
            }

            private int bitField0_;

            private com.google.protobuf.ByteString clientIp_ = com.google.protobuf.ByteString.EMPTY;

            /**
             * <code>bytes client_ip = 1;</code>
             *
             * @return The clientIp.
             */
            @Override
            public com.google.protobuf.ByteString getClientIp() {
                return clientIp_;
            }

            /**
             * <code>bytes client_ip = 1;</code>
             *
             * @param value The clientIp to set.
             * @return This builder for chaining.
             */
            public Builder setClientIp(com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                clientIp_ = value;
                bitField0_ |= 0x00000001;
                onChanged();
                return this;
            }

            /**
             * <code>bytes client_ip = 1;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearClientIp() {
                bitField0_ = (bitField0_ & ~0x00000001);
                clientIp_ = getDefaultInstance().getClientIp();
                onChanged();
                return this;
            }

            private com.google.protobuf.ByteString reportIp_ = com.google.protobuf.ByteString.EMPTY;

            /**
             * <code>bytes report_ip = 2;</code>
             *
             * @return The reportIp.
             */
            @Override
            public com.google.protobuf.ByteString getReportIp() {
                return reportIp_;
            }

            /**
             * <code>bytes report_ip = 2;</code>
             *
             * @param value The reportIp to set.
             * @return This builder for chaining.
             */
            public Builder setReportIp(com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                reportIp_ = value;
                bitField0_ |= 0x00000002;
                onChanged();
                return this;
            }

            /**
             * <code>bytes report_ip = 2;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearReportIp() {
                bitField0_ = (bitField0_ & ~0x00000002);
                reportIp_ = getDefaultInstance().getReportIp();
                onChanged();
                return this;
            }

            private com.google.protobuf.ByteString reportV4_ = com.google.protobuf.ByteString.EMPTY;

            /**
             * <code>bytes report_v4 = 3;</code>
             *
             * @return The reportV4.
             */
            @Override
            public com.google.protobuf.ByteString getReportV4() {
                return reportV4_;
            }

            /**
             * <code>bytes report_v4 = 3;</code>
             *
             * @param value The reportV4 to set.
             * @return This builder for chaining.
             */
            public Builder setReportV4(com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                reportV4_ = value;
                bitField0_ |= 0x00000004;
                onChanged();
                return this;
            }

            /**
             * <code>bytes report_v4 = 3;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearReportV4() {
                bitField0_ = (bitField0_ & ~0x00000004);
                reportV4_ = getDefaultInstance().getReportV4();
                onChanged();
                return this;
            }

            private com.google.protobuf.ByteString reportV6_ = com.google.protobuf.ByteString.EMPTY;

            /**
             * <code>bytes report_v6 = 4;</code>
             *
             * @return The reportV6.
             */
            @Override
            public com.google.protobuf.ByteString getReportV6() {
                return reportV6_;
            }

            /**
             * <code>bytes report_v6 = 4;</code>
             *
             * @param value The reportV6 to set.
             * @return This builder for chaining.
             */
            public Builder setReportV6(com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                reportV6_ = value;
                bitField0_ |= 0x00000008;
                onChanged();
                return this;
            }

            /**
             * <code>bytes report_v6 = 4;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearReportV6() {
                bitField0_ = (bitField0_ & ~0x00000008);
                reportV6_ = getDefaultInstance().getReportV6();
                onChanged();
                return this;
            }

            // @@protoc_insertion_point(builder_scope:IPInfo)
        }

        // @@protoc_insertion_point(class_scope:IPInfo)
        private static final IPInfo DEFAULT_INSTANCE;

        static {
            DEFAULT_INSTANCE = new IPInfo();
        }

        public static IPInfo getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        private static final com.google.protobuf.Parser<IPInfo>
                PARSER = new com.google.protobuf.AbstractParser<IPInfo>() {
            @Override
            public IPInfo parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                Builder builder = newBuilder();
                try {
                    builder.mergeFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    throw e.setUnfinishedMessage(builder.buildPartial());
                } catch (com.google.protobuf.UninitializedMessageException e) {
                    throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
                } catch (java.io.IOException e) {
                    throw new com.google.protobuf.InvalidProtocolBufferException(e)
                            .setUnfinishedMessage(builder.buildPartial());
                }
                return builder.buildPartial();
            }
        };

        public static com.google.protobuf.Parser<IPInfo> parser() {
            return PARSER;
        }

        @Override
        public com.google.protobuf.Parser<IPInfo> getParserForType() {
            return PARSER;
        }

        @Override
        public IPInfo getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    public interface PeerInfoOrBuilder extends
            // @@protoc_insertion_point(interface_extends:PeerInfo)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>bytes info_hash = 1;</code>
         *
         * @return The infoHash.
         */
        com.google.protobuf.ByteString getInfoHash();

        /**
         * <code>.IPInfo ip = 2;</code>
         *
         * @return Whether the ip field is set.
         */
        boolean hasIp();

        /**
         * <code>.IPInfo ip = 2;</code>
         *
         * @return The ip.
         */
        IPInfo getIp();

        /**
         * <code>.IPInfo ip = 2;</code>
         */
        IPInfoOrBuilder getIpOrBuilder();

        /**
         * <code>int32 port = 3;</code>
         *
         * @return The port.
         */
        int getPort();

        /**
         * <code>uint64 left = 4;</code>
         *
         * @return The left.
         */
        long getLeft();

        /**
         * <code>uint64 downloaded = 5;</code>
         *
         * @return The downloaded.
         */
        long getDownloaded();

        /**
         * <code>uint64 uploaded = 6;</code>
         *
         * @return The uploaded.
         */
        long getUploaded();

        /**
         * <code>int64 lastSeen = 7;</code>
         *
         * @return The lastSeen.
         */
        long getLastSeen();

        /**
         * <code>string user_agent = 8;</code>
         *
         * @return The userAgent.
         */
        String getUserAgent();

        /**
         * <code>string user_agent = 8;</code>
         *
         * @return The bytes for userAgent.
         */
        com.google.protobuf.ByteString
        getUserAgentBytes();

        /**
         * <code>bytes peer_id = 9;</code>
         *
         * @return The peerId.
         */
        com.google.protobuf.ByteString getPeerId();

        /**
         * <code>.PeerEvent event = 10;</code>
         *
         * @return The enum numeric value on the wire for event.
         */
        int getEventValue();

        /**
         * <code>.PeerEvent event = 10;</code>
         *
         * @return The event.
         */
        PeerEvent getEvent();
    }

    /**
     * Protobuf type {@code PeerInfo}
     */
    public static final class PeerInfo extends
            com.google.protobuf.GeneratedMessage implements
            // @@protoc_insertion_point(message_implements:PeerInfo)
            PeerInfoOrBuilder {
        private static final long serialVersionUID = 0L;

        static {
            com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
                    com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
                    /* major= */ 4,
                    /* minor= */ 29,
                    /* patch= */ 1,
                    /* suffix= */ "",
                    PeerInfo.class.getName());
        }

        // Use PeerInfo.newBuilder() to construct.
        private PeerInfo(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
            super(builder);
        }

        private PeerInfo() {
            infoHash_ = com.google.protobuf.ByteString.EMPTY;
            userAgent_ = "";
            peerId_ = com.google.protobuf.ByteString.EMPTY;
            event_ = 0;
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return Peer.internal_static_PeerInfo_descriptor;
        }

        @Override
        protected FieldAccessorTable
        internalGetFieldAccessorTable() {
            return Peer.internal_static_PeerInfo_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            PeerInfo.class, Builder.class);
        }

        private int bitField0_;
        public static final int INFO_HASH_FIELD_NUMBER = 1;
        private com.google.protobuf.ByteString infoHash_ = com.google.protobuf.ByteString.EMPTY;

        /**
         * <code>bytes info_hash = 1;</code>
         *
         * @return The infoHash.
         */
        @Override
        public com.google.protobuf.ByteString getInfoHash() {
            return infoHash_;
        }

        public static final int IP_FIELD_NUMBER = 2;
        private IPInfo ip_;

        /**
         * <code>.IPInfo ip = 2;</code>
         *
         * @return Whether the ip field is set.
         */
        @Override
        public boolean hasIp() {
            return ((bitField0_ & 0x00000001) != 0);
        }

        /**
         * <code>.IPInfo ip = 2;</code>
         *
         * @return The ip.
         */
        @Override
        public IPInfo getIp() {
            return ip_ == null ? IPInfo.getDefaultInstance() : ip_;
        }

        /**
         * <code>.IPInfo ip = 2;</code>
         */
        @Override
        public IPInfoOrBuilder getIpOrBuilder() {
            return ip_ == null ? IPInfo.getDefaultInstance() : ip_;
        }

        public static final int PORT_FIELD_NUMBER = 3;
        private int port_ = 0;

        /**
         * <code>int32 port = 3;</code>
         *
         * @return The port.
         */
        @Override
        public int getPort() {
            return port_;
        }

        public static final int LEFT_FIELD_NUMBER = 4;
        private long left_ = 0L;

        /**
         * <code>uint64 left = 4;</code>
         *
         * @return The left.
         */
        @Override
        public long getLeft() {
            return left_;
        }

        public static final int DOWNLOADED_FIELD_NUMBER = 5;
        private long downloaded_ = 0L;

        /**
         * <code>uint64 downloaded = 5;</code>
         *
         * @return The downloaded.
         */
        @Override
        public long getDownloaded() {
            return downloaded_;
        }

        public static final int UPLOADED_FIELD_NUMBER = 6;
        private long uploaded_ = 0L;

        /**
         * <code>uint64 uploaded = 6;</code>
         *
         * @return The uploaded.
         */
        @Override
        public long getUploaded() {
            return uploaded_;
        }

        public static final int LASTSEEN_FIELD_NUMBER = 7;
        private long lastSeen_ = 0L;

        /**
         * <code>int64 lastSeen = 7;</code>
         *
         * @return The lastSeen.
         */
        @Override
        public long getLastSeen() {
            return lastSeen_;
        }

        public static final int USER_AGENT_FIELD_NUMBER = 8;
        @SuppressWarnings("serial")
        private volatile Object userAgent_ = "";

        /**
         * <code>string user_agent = 8;</code>
         *
         * @return The userAgent.
         */
        @Override
        public String getUserAgent() {
            Object ref = userAgent_;
            if (ref instanceof String) {
                return (String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                userAgent_ = s;
                return s;
            }
        }

        /**
         * <code>string user_agent = 8;</code>
         *
         * @return The bytes for userAgent.
         */
        @Override
        public com.google.protobuf.ByteString
        getUserAgentBytes() {
            Object ref = userAgent_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                userAgent_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int PEER_ID_FIELD_NUMBER = 9;
        private com.google.protobuf.ByteString peerId_ = com.google.protobuf.ByteString.EMPTY;

        /**
         * <code>bytes peer_id = 9;</code>
         *
         * @return The peerId.
         */
        @Override
        public com.google.protobuf.ByteString getPeerId() {
            return peerId_;
        }

        public static final int EVENT_FIELD_NUMBER = 10;
        private int event_ = 0;

        /**
         * <code>.PeerEvent event = 10;</code>
         *
         * @return The enum numeric value on the wire for event.
         */
        @Override
        public int getEventValue() {
            return event_;
        }

        /**
         * <code>.PeerEvent event = 10;</code>
         *
         * @return The event.
         */
        @Override
        public PeerEvent getEvent() {
            PeerEvent result = PeerEvent.forNumber(event_);
            return result == null ? PeerEvent.UNRECOGNIZED : result;
        }

        private byte memoizedIsInitialized = -1;

        @Override
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        @Override
        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (!infoHash_.isEmpty()) {
                output.writeBytes(1, infoHash_);
            }
            if (((bitField0_ & 0x00000001) != 0)) {
                output.writeMessage(2, getIp());
            }
            if (port_ != 0) {
                output.writeInt32(3, port_);
            }
            if (left_ != 0L) {
                output.writeUInt64(4, left_);
            }
            if (downloaded_ != 0L) {
                output.writeUInt64(5, downloaded_);
            }
            if (uploaded_ != 0L) {
                output.writeUInt64(6, uploaded_);
            }
            if (lastSeen_ != 0L) {
                output.writeInt64(7, lastSeen_);
            }
            if (!com.google.protobuf.GeneratedMessage.isStringEmpty(userAgent_)) {
                com.google.protobuf.GeneratedMessage.writeString(output, 8, userAgent_);
            }
            if (!peerId_.isEmpty()) {
                output.writeBytes(9, peerId_);
            }
            if (event_ != PeerEvent.Unknown.getNumber()) {
                output.writeEnum(10, event_);
            }
            getUnknownFields().writeTo(output);
        }

        @Override
        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (!infoHash_.isEmpty()) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBytesSize(1, infoHash_);
            }
            if (((bitField0_ & 0x00000001) != 0)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeMessageSize(2, getIp());
            }
            if (port_ != 0) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt32Size(3, port_);
            }
            if (left_ != 0L) {
                size += com.google.protobuf.CodedOutputStream
                        .computeUInt64Size(4, left_);
            }
            if (downloaded_ != 0L) {
                size += com.google.protobuf.CodedOutputStream
                        .computeUInt64Size(5, downloaded_);
            }
            if (uploaded_ != 0L) {
                size += com.google.protobuf.CodedOutputStream
                        .computeUInt64Size(6, uploaded_);
            }
            if (lastSeen_ != 0L) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt64Size(7, lastSeen_);
            }
            if (!com.google.protobuf.GeneratedMessage.isStringEmpty(userAgent_)) {
                size += com.google.protobuf.GeneratedMessage.computeStringSize(8, userAgent_);
            }
            if (!peerId_.isEmpty()) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBytesSize(9, peerId_);
            }
            if (event_ != PeerEvent.Unknown.getNumber()) {
                size += com.google.protobuf.CodedOutputStream
                        .computeEnumSize(10, event_);
            }
            size += getUnknownFields().getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @Override
        public boolean equals(final Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof PeerInfo)) {
                return super.equals(obj);
            }
            PeerInfo other = (PeerInfo) obj;

            if (!getInfoHash()
                    .equals(other.getInfoHash())) return false;
            if (hasIp() != other.hasIp()) return false;
            if (hasIp()) {
                if (!getIp()
                        .equals(other.getIp())) return false;
            }
            if (getPort()
                    != other.getPort()) return false;
            if (getLeft()
                    != other.getLeft()) return false;
            if (getDownloaded()
                    != other.getDownloaded()) return false;
            if (getUploaded()
                    != other.getUploaded()) return false;
            if (getLastSeen()
                    != other.getLastSeen()) return false;
            if (!getUserAgent()
                    .equals(other.getUserAgent())) return false;
            if (!getPeerId()
                    .equals(other.getPeerId())) return false;
            if (event_ != other.event_) return false;
            if (!getUnknownFields().equals(other.getUnknownFields())) return false;
            return true;
        }

        @Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            hash = (37 * hash) + INFO_HASH_FIELD_NUMBER;
            hash = (53 * hash) + getInfoHash().hashCode();
            if (hasIp()) {
                hash = (37 * hash) + IP_FIELD_NUMBER;
                hash = (53 * hash) + getIp().hashCode();
            }
            hash = (37 * hash) + PORT_FIELD_NUMBER;
            hash = (53 * hash) + getPort();
            hash = (37 * hash) + LEFT_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                    getLeft());
            hash = (37 * hash) + DOWNLOADED_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                    getDownloaded());
            hash = (37 * hash) + UPLOADED_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                    getUploaded());
            hash = (37 * hash) + LASTSEEN_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                    getLastSeen());
            hash = (37 * hash) + USER_AGENT_FIELD_NUMBER;
            hash = (53 * hash) + getUserAgent().hashCode();
            hash = (37 * hash) + PEER_ID_FIELD_NUMBER;
            hash = (53 * hash) + getPeerId().hashCode();
            hash = (37 * hash) + EVENT_FIELD_NUMBER;
            hash = (53 * hash) + event_;
            hash = (29 * hash) + getUnknownFields().hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static PeerInfo parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static PeerInfo parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static PeerInfo parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static PeerInfo parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static PeerInfo parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static PeerInfo parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static PeerInfo parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessage
                    .parseWithIOException(PARSER, input);
        }

        public static PeerInfo parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessage
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static PeerInfo parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessage
                    .parseDelimitedWithIOException(PARSER, input);
        }

        public static PeerInfo parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessage
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }

        public static PeerInfo parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessage
                    .parseWithIOException(PARSER, input);
        }

        public static PeerInfo parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessage
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        @Override
        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(PeerInfo prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        @Override
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @Override
        protected Builder newBuilderForType(
                BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        /**
         * Protobuf type {@code PeerInfo}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessage.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:PeerInfo)
                PeerInfoOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return Peer.internal_static_PeerInfo_descriptor;
            }

            @Override
            protected FieldAccessorTable
            internalGetFieldAccessorTable() {
                return Peer.internal_static_PeerInfo_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                PeerInfo.class, Builder.class);
            }

            // Construct using Peer.PeerInfo.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessage
                        .alwaysUseFieldBuilders) {
                    getIpFieldBuilder();
                }
            }

            @Override
            public Builder clear() {
                super.clear();
                bitField0_ = 0;
                infoHash_ = com.google.protobuf.ByteString.EMPTY;
                ip_ = null;
                if (ipBuilder_ != null) {
                    ipBuilder_.dispose();
                    ipBuilder_ = null;
                }
                port_ = 0;
                left_ = 0L;
                downloaded_ = 0L;
                uploaded_ = 0L;
                lastSeen_ = 0L;
                userAgent_ = "";
                peerId_ = com.google.protobuf.ByteString.EMPTY;
                event_ = 0;
                return this;
            }

            @Override
            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return Peer.internal_static_PeerInfo_descriptor;
            }

            @Override
            public PeerInfo getDefaultInstanceForType() {
                return PeerInfo.getDefaultInstance();
            }

            @Override
            public PeerInfo build() {
                PeerInfo result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            @Override
            public PeerInfo buildPartial() {
                PeerInfo result = new PeerInfo(this);
                if (bitField0_ != 0) {
                    buildPartial0(result);
                }
                onBuilt();
                return result;
            }

            private void buildPartial0(PeerInfo result) {
                int from_bitField0_ = bitField0_;
                if (((from_bitField0_ & 0x00000001) != 0)) {
                    result.infoHash_ = infoHash_;
                }
                int to_bitField0_ = 0;
                if (((from_bitField0_ & 0x00000002) != 0)) {
                    result.ip_ = ipBuilder_ == null
                            ? ip_
                            : ipBuilder_.build();
                    to_bitField0_ |= 0x00000001;
                }
                if (((from_bitField0_ & 0x00000004) != 0)) {
                    result.port_ = port_;
                }
                if (((from_bitField0_ & 0x00000008) != 0)) {
                    result.left_ = left_;
                }
                if (((from_bitField0_ & 0x00000010) != 0)) {
                    result.downloaded_ = downloaded_;
                }
                if (((from_bitField0_ & 0x00000020) != 0)) {
                    result.uploaded_ = uploaded_;
                }
                if (((from_bitField0_ & 0x00000040) != 0)) {
                    result.lastSeen_ = lastSeen_;
                }
                if (((from_bitField0_ & 0x00000080) != 0)) {
                    result.userAgent_ = userAgent_;
                }
                if (((from_bitField0_ & 0x00000100) != 0)) {
                    result.peerId_ = peerId_;
                }
                if (((from_bitField0_ & 0x00000200) != 0)) {
                    result.event_ = event_;
                }
                result.bitField0_ |= to_bitField0_;
            }

            @Override
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof PeerInfo) {
                    return mergeFrom((PeerInfo) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(PeerInfo other) {
                if (other == PeerInfo.getDefaultInstance()) return this;
                if (other.getInfoHash() != com.google.protobuf.ByteString.EMPTY) {
                    setInfoHash(other.getInfoHash());
                }
                if (other.hasIp()) {
                    mergeIp(other.getIp());
                }
                if (other.getPort() != 0) {
                    setPort(other.getPort());
                }
                if (other.getLeft() != 0L) {
                    setLeft(other.getLeft());
                }
                if (other.getDownloaded() != 0L) {
                    setDownloaded(other.getDownloaded());
                }
                if (other.getUploaded() != 0L) {
                    setUploaded(other.getUploaded());
                }
                if (other.getLastSeen() != 0L) {
                    setLastSeen(other.getLastSeen());
                }
                if (!other.getUserAgent().isEmpty()) {
                    userAgent_ = other.userAgent_;
                    bitField0_ |= 0x00000080;
                    onChanged();
                }
                if (other.getPeerId() != com.google.protobuf.ByteString.EMPTY) {
                    setPeerId(other.getPeerId());
                }
                if (other.event_ != 0) {
                    setEventValue(other.getEventValue());
                }
                this.mergeUnknownFields(other.getUnknownFields());
                onChanged();
                return this;
            }

            @Override
            public final boolean isInitialized() {
                return true;
            }

            @Override
            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                if (extensionRegistry == null) {
                    throw new NullPointerException();
                }
                try {
                    boolean done = false;
                    while (!done) {
                        int tag = input.readTag();
                        switch (tag) {
                            case 0:
                                done = true;
                                break;
                            case 10: {
                                infoHash_ = input.readBytes();
                                bitField0_ |= 0x00000001;
                                break;
                            } // case 10
                            case 18: {
                                input.readMessage(
                                        getIpFieldBuilder().getBuilder(),
                                        extensionRegistry);
                                bitField0_ |= 0x00000002;
                                break;
                            } // case 18
                            case 24: {
                                port_ = input.readInt32();
                                bitField0_ |= 0x00000004;
                                break;
                            } // case 24
                            case 32: {
                                left_ = input.readUInt64();
                                bitField0_ |= 0x00000008;
                                break;
                            } // case 32
                            case 40: {
                                downloaded_ = input.readUInt64();
                                bitField0_ |= 0x00000010;
                                break;
                            } // case 40
                            case 48: {
                                uploaded_ = input.readUInt64();
                                bitField0_ |= 0x00000020;
                                break;
                            } // case 48
                            case 56: {
                                lastSeen_ = input.readInt64();
                                bitField0_ |= 0x00000040;
                                break;
                            } // case 56
                            case 66: {
                                userAgent_ = input.readStringRequireUtf8();
                                bitField0_ |= 0x00000080;
                                break;
                            } // case 66
                            case 74: {
                                peerId_ = input.readBytes();
                                bitField0_ |= 0x00000100;
                                break;
                            } // case 74
                            case 80: {
                                event_ = input.readEnum();
                                bitField0_ |= 0x00000200;
                                break;
                            } // case 80
                            default: {
                                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                                    done = true; // was an endgroup tag
                                }
                                break;
                            } // default:
                        } // switch (tag)
                    } // while (!done)
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    throw e.unwrapIOException();
                } finally {
                    onChanged();
                } // finally
                return this;
            }

            private int bitField0_;

            private com.google.protobuf.ByteString infoHash_ = com.google.protobuf.ByteString.EMPTY;

            /**
             * <code>bytes info_hash = 1;</code>
             *
             * @return The infoHash.
             */
            @Override
            public com.google.protobuf.ByteString getInfoHash() {
                return infoHash_;
            }

            /**
             * <code>bytes info_hash = 1;</code>
             *
             * @param value The infoHash to set.
             * @return This builder for chaining.
             */
            public Builder setInfoHash(com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                infoHash_ = value;
                bitField0_ |= 0x00000001;
                onChanged();
                return this;
            }

            /**
             * <code>bytes info_hash = 1;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearInfoHash() {
                bitField0_ = (bitField0_ & ~0x00000001);
                infoHash_ = getDefaultInstance().getInfoHash();
                onChanged();
                return this;
            }

            private IPInfo ip_;
            private com.google.protobuf.SingleFieldBuilder<
                    IPInfo, IPInfo.Builder, IPInfoOrBuilder> ipBuilder_;

            /**
             * <code>.IPInfo ip = 2;</code>
             *
             * @return Whether the ip field is set.
             */
            public boolean hasIp() {
                return ((bitField0_ & 0x00000002) != 0);
            }

            /**
             * <code>.IPInfo ip = 2;</code>
             *
             * @return The ip.
             */
            public IPInfo getIp() {
                if (ipBuilder_ == null) {
                    return ip_ == null ? IPInfo.getDefaultInstance() : ip_;
                } else {
                    return ipBuilder_.getMessage();
                }
            }

            /**
             * <code>.IPInfo ip = 2;</code>
             */
            public Builder setIp(IPInfo value) {
                if (ipBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    ip_ = value;
                } else {
                    ipBuilder_.setMessage(value);
                }
                bitField0_ |= 0x00000002;
                onChanged();
                return this;
            }

            /**
             * <code>.IPInfo ip = 2;</code>
             */
            public Builder setIp(
                    IPInfo.Builder builderForValue) {
                if (ipBuilder_ == null) {
                    ip_ = builderForValue.build();
                } else {
                    ipBuilder_.setMessage(builderForValue.build());
                }
                bitField0_ |= 0x00000002;
                onChanged();
                return this;
            }

            /**
             * <code>.IPInfo ip = 2;</code>
             */
            public Builder mergeIp(IPInfo value) {
                if (ipBuilder_ == null) {
                    if (((bitField0_ & 0x00000002) != 0) &&
                            ip_ != null &&
                            ip_ != IPInfo.getDefaultInstance()) {
                        getIpBuilder().mergeFrom(value);
                    } else {
                        ip_ = value;
                    }
                } else {
                    ipBuilder_.mergeFrom(value);
                }
                if (ip_ != null) {
                    bitField0_ |= 0x00000002;
                    onChanged();
                }
                return this;
            }

            /**
             * <code>.IPInfo ip = 2;</code>
             */
            public Builder clearIp() {
                bitField0_ = (bitField0_ & ~0x00000002);
                ip_ = null;
                if (ipBuilder_ != null) {
                    ipBuilder_.dispose();
                    ipBuilder_ = null;
                }
                onChanged();
                return this;
            }

            /**
             * <code>.IPInfo ip = 2;</code>
             */
            public IPInfo.Builder getIpBuilder() {
                bitField0_ |= 0x00000002;
                onChanged();
                return getIpFieldBuilder().getBuilder();
            }

            /**
             * <code>.IPInfo ip = 2;</code>
             */
            public IPInfoOrBuilder getIpOrBuilder() {
                if (ipBuilder_ != null) {
                    return ipBuilder_.getMessageOrBuilder();
                } else {
                    return ip_ == null ?
                            IPInfo.getDefaultInstance() : ip_;
                }
            }

            /**
             * <code>.IPInfo ip = 2;</code>
             */
            private com.google.protobuf.SingleFieldBuilder<
                    IPInfo, IPInfo.Builder, IPInfoOrBuilder>
            getIpFieldBuilder() {
                if (ipBuilder_ == null) {
                    ipBuilder_ = new com.google.protobuf.SingleFieldBuilder<
                            IPInfo, IPInfo.Builder, IPInfoOrBuilder>(
                            getIp(),
                            getParentForChildren(),
                            isClean());
                    ip_ = null;
                }
                return ipBuilder_;
            }

            private int port_;

            /**
             * <code>int32 port = 3;</code>
             *
             * @return The port.
             */
            @Override
            public int getPort() {
                return port_;
            }

            /**
             * <code>int32 port = 3;</code>
             *
             * @param value The port to set.
             * @return This builder for chaining.
             */
            public Builder setPort(int value) {

                port_ = value;
                bitField0_ |= 0x00000004;
                onChanged();
                return this;
            }

            /**
             * <code>int32 port = 3;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearPort() {
                bitField0_ = (bitField0_ & ~0x00000004);
                port_ = 0;
                onChanged();
                return this;
            }

            private long left_;

            /**
             * <code>uint64 left = 4;</code>
             *
             * @return The left.
             */
            @Override
            public long getLeft() {
                return left_;
            }

            /**
             * <code>uint64 left = 4;</code>
             *
             * @param value The left to set.
             * @return This builder for chaining.
             */
            public Builder setLeft(long value) {

                left_ = value;
                bitField0_ |= 0x00000008;
                onChanged();
                return this;
            }

            /**
             * <code>uint64 left = 4;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearLeft() {
                bitField0_ = (bitField0_ & ~0x00000008);
                left_ = 0L;
                onChanged();
                return this;
            }

            private long downloaded_;

            /**
             * <code>uint64 downloaded = 5;</code>
             *
             * @return The downloaded.
             */
            @Override
            public long getDownloaded() {
                return downloaded_;
            }

            /**
             * <code>uint64 downloaded = 5;</code>
             *
             * @param value The downloaded to set.
             * @return This builder for chaining.
             */
            public Builder setDownloaded(long value) {

                downloaded_ = value;
                bitField0_ |= 0x00000010;
                onChanged();
                return this;
            }

            /**
             * <code>uint64 downloaded = 5;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearDownloaded() {
                bitField0_ = (bitField0_ & ~0x00000010);
                downloaded_ = 0L;
                onChanged();
                return this;
            }

            private long uploaded_;

            /**
             * <code>uint64 uploaded = 6;</code>
             *
             * @return The uploaded.
             */
            @Override
            public long getUploaded() {
                return uploaded_;
            }

            /**
             * <code>uint64 uploaded = 6;</code>
             *
             * @param value The uploaded to set.
             * @return This builder for chaining.
             */
            public Builder setUploaded(long value) {

                uploaded_ = value;
                bitField0_ |= 0x00000020;
                onChanged();
                return this;
            }

            /**
             * <code>uint64 uploaded = 6;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearUploaded() {
                bitField0_ = (bitField0_ & ~0x00000020);
                uploaded_ = 0L;
                onChanged();
                return this;
            }

            private long lastSeen_;

            /**
             * <code>int64 lastSeen = 7;</code>
             *
             * @return The lastSeen.
             */
            @Override
            public long getLastSeen() {
                return lastSeen_;
            }

            /**
             * <code>int64 lastSeen = 7;</code>
             *
             * @param value The lastSeen to set.
             * @return This builder for chaining.
             */
            public Builder setLastSeen(long value) {

                lastSeen_ = value;
                bitField0_ |= 0x00000040;
                onChanged();
                return this;
            }

            /**
             * <code>int64 lastSeen = 7;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearLastSeen() {
                bitField0_ = (bitField0_ & ~0x00000040);
                lastSeen_ = 0L;
                onChanged();
                return this;
            }

            private Object userAgent_ = "";

            /**
             * <code>string user_agent = 8;</code>
             *
             * @return The userAgent.
             */
            public String getUserAgent() {
                Object ref = userAgent_;
                if (!(ref instanceof String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    String s = bs.toStringUtf8();
                    userAgent_ = s;
                    return s;
                } else {
                    return (String) ref;
                }
            }

            /**
             * <code>string user_agent = 8;</code>
             *
             * @return The bytes for userAgent.
             */
            public com.google.protobuf.ByteString
            getUserAgentBytes() {
                Object ref = userAgent_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (String) ref);
                    userAgent_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>string user_agent = 8;</code>
             *
             * @param value The userAgent to set.
             * @return This builder for chaining.
             */
            public Builder setUserAgent(
                    String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                userAgent_ = value;
                bitField0_ |= 0x00000080;
                onChanged();
                return this;
            }

            /**
             * <code>string user_agent = 8;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearUserAgent() {
                userAgent_ = getDefaultInstance().getUserAgent();
                bitField0_ = (bitField0_ & ~0x00000080);
                onChanged();
                return this;
            }

            /**
             * <code>string user_agent = 8;</code>
             *
             * @param value The bytes for userAgent to set.
             * @return This builder for chaining.
             */
            public Builder setUserAgentBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);
                userAgent_ = value;
                bitField0_ |= 0x00000080;
                onChanged();
                return this;
            }

            private com.google.protobuf.ByteString peerId_ = com.google.protobuf.ByteString.EMPTY;

            /**
             * <code>bytes peer_id = 9;</code>
             *
             * @return The peerId.
             */
            @Override
            public com.google.protobuf.ByteString getPeerId() {
                return peerId_;
            }

            /**
             * <code>bytes peer_id = 9;</code>
             *
             * @param value The peerId to set.
             * @return This builder for chaining.
             */
            public Builder setPeerId(com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                peerId_ = value;
                bitField0_ |= 0x00000100;
                onChanged();
                return this;
            }

            /**
             * <code>bytes peer_id = 9;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearPeerId() {
                bitField0_ = (bitField0_ & ~0x00000100);
                peerId_ = getDefaultInstance().getPeerId();
                onChanged();
                return this;
            }

            private int event_ = 0;

            /**
             * <code>.PeerEvent event = 10;</code>
             *
             * @return The enum numeric value on the wire for event.
             */
            @Override
            public int getEventValue() {
                return event_;
            }

            /**
             * <code>.PeerEvent event = 10;</code>
             *
             * @param value The enum numeric value on the wire for event to set.
             * @return This builder for chaining.
             */
            public Builder setEventValue(int value) {
                event_ = value;
                bitField0_ |= 0x00000200;
                onChanged();
                return this;
            }

            /**
             * <code>.PeerEvent event = 10;</code>
             *
             * @return The event.
             */
            @Override
            public PeerEvent getEvent() {
                PeerEvent result = PeerEvent.forNumber(event_);
                return result == null ? PeerEvent.UNRECOGNIZED : result;
            }

            /**
             * <code>.PeerEvent event = 10;</code>
             *
             * @param value The event to set.
             * @return This builder for chaining.
             */
            public Builder setEvent(PeerEvent value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000200;
                event_ = value.getNumber();
                onChanged();
                return this;
            }

            /**
             * <code>.PeerEvent event = 10;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearEvent() {
                bitField0_ = (bitField0_ & ~0x00000200);
                event_ = 0;
                onChanged();
                return this;
            }

            // @@protoc_insertion_point(builder_scope:PeerInfo)
        }

        // @@protoc_insertion_point(class_scope:PeerInfo)
        private static final PeerInfo DEFAULT_INSTANCE;

        static {
            DEFAULT_INSTANCE = new PeerInfo();
        }

        public static PeerInfo getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        private static final com.google.protobuf.Parser<PeerInfo>
                PARSER = new com.google.protobuf.AbstractParser<PeerInfo>() {
            @Override
            public PeerInfo parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                Builder builder = newBuilder();
                try {
                    builder.mergeFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    throw e.setUnfinishedMessage(builder.buildPartial());
                } catch (com.google.protobuf.UninitializedMessageException e) {
                    throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
                } catch (java.io.IOException e) {
                    throw new com.google.protobuf.InvalidProtocolBufferException(e)
                            .setUnfinishedMessage(builder.buildPartial());
                }
                return builder.buildPartial();
            }
        };

        public static com.google.protobuf.Parser<PeerInfo> parser() {
            return PARSER;
        }

        @Override
        public com.google.protobuf.Parser<PeerInfo> getParserForType() {
            return PARSER;
        }

        @Override
        public PeerInfo getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_IPInfo_descriptor;
    private static final
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internal_static_IPInfo_fieldAccessorTable;
    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_PeerInfo_descriptor;
    private static final
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internal_static_PeerInfo_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }

    private static com.google.protobuf.Descriptors.FileDescriptor
            descriptor;

    static {
        String[] descriptorData = {
                "\n\npeer.proto\"T\n\006IPInfo\022\021\n\tclient_ip\030\001 \001(" +
                        "\014\022\021\n\treport_ip\030\002 \001(\014\022\021\n\treport_v4\030\003 \001(\014\022" +
                        "\021\n\treport_v6\030\004 \001(\014\"\306\001\n\010PeerInfo\022\021\n\tinfo_" +
                        "hash\030\001 \001(\014\022\023\n\002ip\030\002 \001(\0132\007.IPInfo\022\014\n\004port\030" +
                        "\003 \001(\005\022\014\n\004left\030\004 \001(\004\022\022\n\ndownloaded\030\005 \001(\004\022" +
                        "\020\n\010uploaded\030\006 \001(\004\022\020\n\010lastSeen\030\007 \001(\003\022\022\n\nu" +
                        "ser_agent\030\010 \001(\t\022\017\n\007peer_id\030\t \001(\014\022\031\n\005even" +
                        "t\030\n \001(\0162\n.PeerEvent*A\n\tPeerEvent\022\013\n\007Unkn" +
                        "own\020\000\022\013\n\007Started\020\001\022\013\n\007Stopped\020\002\022\r\n\tCompl" +
                        "eted\020\003B\035Z\033biz/services/peer/mux_localb\006p" +
                        "roto3"
        };
        descriptor = com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[]{
                        });
        internal_static_IPInfo_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_IPInfo_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessage.FieldAccessorTable(
                internal_static_IPInfo_descriptor,
                new String[]{"ClientIp", "ReportIp", "ReportV4", "ReportV6",});
        internal_static_PeerInfo_descriptor =
                getDescriptor().getMessageTypes().get(1);
        internal_static_PeerInfo_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessage.FieldAccessorTable(
                internal_static_PeerInfo_descriptor,
                new String[]{"InfoHash", "Ip", "Port", "Left", "Downloaded", "Uploaded", "LastSeen", "UserAgent", "PeerId", "Event",});
        descriptor.resolveAllFeaturesImmutable();
    }

    // @@protoc_insertion_point(outer_class_scope)
}
